# 日志配置
logging:
  level:
    root: debug
    # 关闭下面冗余的日志
    org.apache.http: off
    org.apache.commons: off
    org.eclipse.jetty: off
    io.lettuce: off
    io.netty: off
    reactor.netty: off
    sun.rmi: off
